import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

// const SPREADSHEET_ID = process.env.REACT_APP_SPREADSHEET_ID;
// const CLIENT_EMAIL = process.env.REACT_APP_GOOGLE_CLIENT_EMAIL;
// const PRIVATE_KEY = process.env.REACT_APP_GOOGLE_PRIVATE_KEY?.replace(
//   /\\n/g,
//   "\n"
// );

export async function getSheet() {
  try {
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: 'iam-be@monitoring-imigrasi.iam.gserviceaccount.com',
      key: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDVFoEHbQnZ3lHA\nWfeA+SMfm+Sl/zrCUkLEVu0Z8+Ez3NgGccgSmK5eShMJ4F4ic27sjtcWOIydXeaI\ntugri4qxqdaUwsTBG+D9tvXzyIRX8ZkHVi0T+o/tfv77ee3JwI0fyU6XjYyYCQ9Y\nk+lzCDGMzZGDBMMzpQd/wujLqzqFig4h+u+b4cN+MLzI/Jv8U3CT3oaJFtvOk9dW\n+ZioJudC80T5M7UGCnPiuwfDnl8LcJH9D69RyykzgH2CzpRvyo8VHp7I8y+Rd0xa\nAgFqNC5zVyy9Int3B54BpgEEZx/MCnOtdv9a4iQvbdhFrSULrFwL/myDvbyNHhaf\nHHgp8xD7AgMBAAECggEABotn5W9TD6F1N6gBDYbZWNBZaphsWL6HtW8JXjQwKlRx\n6r9rioKs9vwQb0u4UxeM2cVzVAfi7bcOFwyDFJ9MYF4xLHrPlIduLBdb9iOmSOsv\nLNtX4WwJ0pywE8+FXvPD1yzqyzB6QnXOG7At9INVE5gsDBmagzIM3mmBQTbI7S6n\nbn8TqwahkwtwqVSv75Yp8JGp/tqpnoXUn0qYdOjEAI38lbEq4txnEtHsBfIvVbpt\nuzSELuuYrwMLj7TvFayM8PN8Etf+A50hNBh3e3t9zAkTQBjTYZ4sS5/klf/pjJdY\n99lcfi/pqmuY1vtBEBD0/u/xEnAy0WHzseIY38MCoQKBgQD09Y2s73cGTj0h2weU\nD3bDDnweDRhb8RsUHUy7keD3EXiUGyUkgdaHdNy+FC814ZCSCaGOflHRO7vlCLxm\nyu8vFui0UFxiDiLfMHNfXSyJGaTc6af32acWkXxoL9nZtNokdLNgkJb5Ho0oTplW\nABpHV/Mh2XnG62x6qY7Uaqc9WwKBgQDesTSp9HiRb1Roh73iTr0Ru8jjkyn1FXs+\n1SE/a7ZmuvdrXCCto04RdCocACtmTsRn8vmJNbAgHs41upijYZ9/xH/vDOCLjf60\n3YsKbtZuvh/dl9HUIRyKAe8F8lAn3N3obqCEM95GboPlE10lV1PLlgP0yfE3CUWe\nxzigeses4QKBgHeZhKjQ6m47uQFUraiOvE+UPOl3P1N0ruHtRE+4c/xtnU/CySm/\n8vyEBFsSA9Ls5OdIqIaoCk58OcsjrskJgCqfptKTAegmOsR6JXqERYBS8vmhY49R\nx5DvS6ya4GS5NmDiUcpuDihn0EfDyH4C4tG+kUkPo7OJspdZPhFcWXdNAoGAdeHQ\nQvdKq5IHWJ4igh20MCL7oJxSZY5Ng2FHDE90asUmHArUsZX0yYB4mgHs92dSyMPy\nHBPze81S01ZHXpVa3UOjhWOHqdgssIlmBMvPbyftrlujk2tDtDp50OgITlG4lkWZ\nauIaE6aE40pw0Ed98BMlXPtZWQzrcbV74FeeQ4ECgYBhz3MTy7iQU4ygpU9efYC3\nJphSqgCQJdD6wkqZl8rwvHHSucm70L9YFJw0QCYZntk2XTg5QKWSmja/dWQRHpYX\nTF/fuW+bQm/uwdbdXixe9M46Za4YfBRINrrl5ztsYC0KuEEfBWonqU3yCY1lTCIS\n7qQgx6JSKV4slP85+SSPDQ==\n-----END PRIVATE KEY-----\n",
      scopes: ["https://www.googleapis.com/auth/spreadsheets"],
    });

    const doc = new GoogleSpreadsheet(
      "1ilfh51A78xXq1-tN2yHXY5FC_JdcuFXm9aIaSVJs0Sw",
      serviceAccountAuth
    );
    await doc.loadInfo();
    const sheet = doc.sheetsByIndex[0]; // Adjust index or use sheetsById
    const rows = await sheet.getRows();
    const data = rows.map((row) => row._rawData); // Adjust based on your sheet structure
    return data;
  } catch (error) {
    console.error("Error fetching data:", error);
    throw error;
  }
}
